---
title: "Conclusion"
output:
  html_document:
    toc: true
    toc_float: true
    collapsed: false
    number_sections: false
    toc_depth: 1
    #code_folding: hide
---

# Results 
This project has been a modest first step into an investigation into the relationship between income inequality and voter turnout at various levels of analysis.  

At the aggregate level, I have found results that suggest in the 2020 general election, greater income inequality was associated with lower levels of voter turnout at both the state *and* county level, despite convention in the literature.  

However, in my individual-level model for North Carolina, I find that controlling for other factors such as race, party, age, and mobilization, higher county-level income inequality is associated with greater propensity to vote.

# Limitations

The contributions made in this project, unfortunately, suffer from a few critical limitations, which are crucial to acknowledge:  

- Lack of a consistent measure of voter turnout across levels of analysis (and rough estimates in some cases)
- Use of voter files which do not contain certain theoretically interesting variables such as efficacy or income
- Absence of random sampling in individual-level analysis  
- Focus on single election 
- Inability to compare influence of state & county inequality on the individual propensity to vote (North Carolina only)
- Individual-level analysis does not include non-registered but voting-eligible citizens 

Keeping these limitations in mind, we must recognize the results of this project as a step toward a more robust analysis in the future, and take them with a grain of salt.

# Going Forward

A prominent puzzle in the study of income inequality and voter turnout is that the relationship between the two tends to reverse at varying levels of analysis.  While proponents of the "trust" explanation tend to look at state-level data, proponents of the "conflict" theory look at the county-level.  


Going forward, I would like to investigate the role of external political efficacy as a mechanism which may bridge the gap between these two competing theories.  As income inequality grows, Gilens and Page's research suggest political inequality in policy "wins" may also grow.  Thus, non-wealthy Americans may believe they have less influence in government than do the rich, and choose to stay home (as the trust model would also suggest).  However, efficacy may vary along levels of analysis, and Americans may believe they can fight against inequality effectively at the local level, as the levers of power are relatively accessible compared to the state and national levels.  

Of course, this theory would need further development and would likely demand different sources of data than the ones employed in this project.  But, as previously mentioned, this project can serve as a springboard to more robust research on the relationship between income inequality and voter turnout going forward.  

<p>&nbsp;</p>

# Questions?

